server:
  port: 9998
aliyun:
  info:
    accessKeyId:
    accessKeySecret:
  oss:
    endpoint:
    bucketName:
    backUrl:
    fileName:
qiniu:
  info:
    accessKeyId:
    accessKeySecret:
    bucketName:
    path: