server:
  port: 9999
tencent:
  sms:
    appid:
    appkey:
    templateId:
    smsSign:
    expireTime: 5
aliyun:
  info:
    product:
    domain:
    accessKeyId:
    accessKeySecret:
  sms:
    templateCode:
    smsSign: